# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: ["aarch64", "amd64", "armhf", "i386"]
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: nginx_proxy/
        file: nginx_proxy/Dockerfile.modsecurity
        platforms: ${{ matrix.platform }}
        push: false
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/nginx-116-modsecurity-${{ matrix.platform }}:latest

    # - name: Image digest
    #   run: echo ${{ steps.docker_build.outputs.digest }}

    # - name: Test build
    #   uses: home-assistant/builder@master
    #   with:
    #     args: |
    #       --test \
    #       --aarch64 \
    #       --target nginx_proxy/
