# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Test modsecurity build
      uses: home-assistant/builder@master
      with:
        args: |
          --test \
          --all \
          --target modsecurity/

    # - name: Test build
    #   uses: home-assistant/builder@master
    #   with:
    #     args: |
    #       --test \
    #       --aarch64 \
    #       --target nginx_proxy/
